name: ${NAMESPACE}
services:
    data-helper:
        build:
            args:
                DATA_DIRECTORY: ${DATA_DIRECTORY}
            context: .
            dockerfile: Dockerfile.helper
        container_name: ${NAMESPACE}-data-helper
        volumes:
            -   dumps:/dumps
volumes:
    dumps: